### ISSUE TITLE
 提示需要"net 4.8.1"???

### ISSUE THREAD

**Issue by Yue-cn** [Paving-Base/APK-Installer-Classic#33]
![image](https://user-images.githubusercontent.com/79188080/181731319-d4c19392-e633-4bb7-9564-7100f537ff79.png)
6

**Comment by wherewhere** [comment]
好家伙，没想到.net4.8.1不能在.net4.8上运行。。。

**Comment by AYue2021** [comment]
关键是4.8.1哪里找的...


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wherewhere ***@***.***&gt;
发送时间: 2022年7月29日 19:25
收件人: Paving-Base/APK-Installer-Classic ***@***.***&gt;
抄送: AYue2021 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Paving-Base/APK-Installer-Classic]  提示需要"net 4.8.1"??? (Issue #33)





 
好家伙，没想到.net4.8.1不能在.net4.8上运行。。。

**Comment by wherewhere** [comment]
坏诶，你为什么有小尾巴

**Comment by wherewhere** [comment]
你用VS2022下载一个.net4.8.1SDK就行了

**Comment by AYue2021** [comment]
www这玩安卓的人大部分偏java了 这不麻烦吗

**Comment by AYue2021** [comment]
我直接从邮箱回复的,Iphone上搜不到Github的手机端（可能是我眼瞎）

**Comment by wherewhere** [comment]
iOS的客户端好像还在测试，不知道现在有没有上架了

**Comment by wherewhere** [comment]
![Screenshot_20220812-004448.jpg](https://user-images.githubusercontent.com/27689196/184188877-6bbffff5-745d-4dfa-a473-14d5019841f8.jpg)

**Comment by wherewhere** [comment]
现在可以装.net4.8.1了(最低要求Windows10 20H2。。。
